### ISSUE TITLE
How to set transparent background?

### ISSUE THREAD

**Issue by anotherkhan** [ramandeep-singh-1983/ngx-powerbi#5] opened 2018-08-04 00:09 UTC
Hi, 

I have a question on the configuration settings, I'd like to set the background transparent. I have updates the component.ts with following:

settings: {
            filterPaneEnabled: false,
            navContentPaneEnabled: true,
            background: this.BackgroundType.Transparent
}

Filter settings seems to work but transparent background config does not work. Could you please let me know how to set background transparent?

Thanks!

**Comment by ramandeep-singh-1983** [comment] 2018-08-06 18:15
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details

let embedConfig = {
    ...
    settings: {
	background: models.BackgroundType.Transparent
    }
};

this.BackgroundType.Transparent won't work. Try models.BackgroundType.Transparent instead, you will need to import the model class from powerbi-client module first

**Comment by anotherkhan** [comment] 2018-08-06 21:55
Thanks for the quick response!

I imported models class from powerbi-client ( import { models } from "powerbi-client" ) and used the settings you mentioned "background: models.BackgroundType.Transparent"

but I am getting following error:

error TS2345: Argument of type '{ type: string; uniqueId: string; embedUrl: string; accessToken: string; settings: { background: ...' is not assignable to parameter of type 'IEmbedConfigurationBase'.
  Types of property 'settings' are incompatible.
    Type '{ background: BackgroundType; }' has no properties in common with type 'ISettings'.

**Comment by ramandeep-singh-1983** [comment] 2018-08-07 03:07
Ah ok, I have seen similar errors before, let me try replicating this. I will get back to you soon.

**Comment by B14m3m3** [comment] 2018-08-13 15:45
I got transparent background working with
```ts
import * as models from 'powerbi-models';
...
embedconfig.settings.background = models.BackgroundType.Transparent;
```
with embedconfig being an instance of IEmbedConfiguration.

The `powerbi-models` is a dependency of your `powerbi-client`, so nothing new to import.

**Comment by B14m3m3** [comment] 2018-08-17 09:54
If the answer is sufficient, the issue should be closed, if the answer is not sufficient @anotherkhan can reopen the issue. @ramandeep-singh-1983

**Comment by ramandeep-singh-1983** [comment] 2018-08-20 07:33
Closing this, @anotherkhan please re-open this if the issue is not fixed. I am working on some samples using the library and will try to include transparent background option in the same too.

**Closed as completed by ramandeep-singh-1983** 2018-08-20 07:33 UTC
Labels: question
