### ISSUE TITLE
Error after upgrade to Angular 9

### ISSUE THREAD

**Issue by SmailHammour** [ramandeep-singh-1983/ngx-powerbi#21] opened 2020-02-11 12:06 UTC
Hello,

After upgrading to Angular 9, I'm getting the following error;

> ERROR in The target entry-point “ngx-powerbi” has missing dependencies: - service

**Comment by SmailHammour** [comment] 2020-02-14 07:39
@ramandeep-singh-1983 could you take a look, please?

**Comment by beradrian** [comment] 2020-02-18 13:01
I need this too. Is there a workaround?

**Comment by ramandeep-singh-1983** [comment] 2020-02-18 14:30
@SmailHammour thanks for reporting this issue. I'll look into it. I haven't worked on this for some time now, looks like I will have to do it now :)

**Comment by beradrian** [comment] 2020-02-19 08:36
It will be good to upgrade the entire library to Angular 9 ;)

**Comment by ramandeep-singh-1983** [comment] 2020-02-19 10:21
Sure, I'll look into that.

**Comment by beradrian** [comment] 2020-02-25 08:22
Do you have a timeframe for that? If it takes too long I can look into it. Thanks!

**Comment by ramandeep-singh-1983** [comment] 2020-02-26 06:00
I'll try to do it shortly, can't commit a timeframe as i am a bit busy these days, but if you have a PR, it will be welcomed :)

**Comment by SmailHammour** [comment] 2020-02-28 12:31
@ramandeep-singh-1983 Any news on this?

**Comment by ramandeep-singh-1983** [comment] 2020-02-29 18:21
@SmailHammour I got a new kid in my house, born yesterday so hard to find time immediately. But I have asked my friend to look into it, hopefully he can fix this coming week. I'll keep this thread updated.

**Comment by beradrian** [comment] 2020-03-01 18:36
Please let me know if he finds the time, otherwise I have the time to prepare a PR this week. Thanks!

**Comment by nartc** [comment] 2020-03-02 18:33
While waiting for @ramandeep-singh-1983 or a PR, people with this issue can apply the following workaround using `patch-package`

1. Install `patch-package` as a `devDependencies`
```
npm i -D patch-package
```

2. Go to `node_modules/ngx_powerbi/lib/ngx-powerbi.service.d.ts` and modify the following:

```typescript
...
import { IEvent } from 'service'; // remove this line
...
handleTileEvents(event: pbiService.IEvent<any>): void; // change IEvent to pbiService.IEvent
```

3. Run `npx patch-package ngx-powerbi` in the terminal
4. Add `postinstall: patch-package` script to `package.json`

**Comment by Geoffrynagy** [comment] 2020-03-03 10:46
Thanks for the workaround, looking forward to the actual fix.

**Comment by ramandeep-singh-1983** [comment] 2020-03-09 10:31
I am now setting up this repo on my newly formatted laptop, so i hope to reproduce this issue and to fix it soon.

**Comment by beradrian** [comment] 2020-03-17 11:26
I created a PR to upgrade this library to Angular 9. https://github.com/ramandeep-singh-1983/ngx-powerbi/pull/23.
I also published this temporarily under [@nibo-ai/ngx-powerbi](https://www.npmjs.com/package/@nibo-ai/ngx-powerbi) - it will be retired as soon as the PR is merged and a new version of this library is published.
Please test and let me know of the outcome.

@ramandeep-singh-1983 if you merge my PR please do not forget to publish the new version in npm repo. I also created a npm script `publish_lib` to do this. Just modify the version under `projects/ngx-powerbi/package.json`.

**Comment by ramandeep-singh-1983** [comment] 2020-03-24 05:44
thanks @beradrian , i will try to review and merge it soon (this week).

**Comment by kamilslusarczyk** [comment] 2020-04-06 05:52
Good morning,

Thanks a ton for this library! @ramandeep-singh-1983 can you please let us know, whether you will have a moment to review @beradrian 's changes? I am wondering if I should use his npm package or wait a bit for merging his PR.

Have a nice day,
Kamil

**Comment by ramandeep-singh-1983** [comment] 2020-04-18 13:22
@kamilslusarczyk i have finally reviewed the PR. I have just gone through the files and not ran it as i don't have Angular 9 setup on my machine right now.

If anyone can test it out and share their feedback here in Angular 9.x, it will be great (i think @kamilslusarczyk has already tested it)!

**Comment by beradrian** [comment] 2020-04-20 09:54
I will answer to your comments at latest by the end of the week.

**Comment by kamilslusarczyk** [comment] 2020-04-30 08:25
I will migrate my app from 8 to 9.1 and will try to use new version of ngx-powerbi library. Will let you know if everything went fine hopefully by end of this weekend.

**Closed as completed** 2020-05-01 05:52 UTC
Labels: enhancement

**Comment by beradrian** [comment] 2020-05-01 09:21
@ramandeep-singh-1983 please do not forget to publish the new version into npm repository. Thanks!

**Comment by GreenMarcus** [comment] 2020-05-04 11:54
Please publish the new version into npm repo. I'm still having this issue of missing dependencies. Thanks in advance!

**Comment by doraymifasola** [comment] 2020-05-05 01:29
Hey @ramandeep-singh-1983 
Please publish to npm repo.
The missing dependencies error is still happening.

Many thanks.

**Comment by ramandeep-singh-1983** [comment] 2020-05-05 20:49
I hope to publish it this week.

**Comment by ramandeep-singh-1983** [comment] 2020-05-06 08:32
Version 3.0.0 has been published, please verify if it works with Angular 9.x and post here, thanks!
Thanks a lot to @beradrian for the PR!

**Comment by ollief87** [comment] 2020-05-06 10:19
You are absolute legends @ramandeep-singh-1983 & @beradrian! Thanks so much, will begin testing soon :-)

**Comment by ramandeep-singh-1983** [comment] 2020-05-11 07:13
@ollief87 thanks for the kind words :) I just tested it with Angular 9.0.5 and it works.
